@startuml

component [Booklist]
component [Book]
component [Booklist Browser]
component [Booklist Editor]
component [Booklist Analyzer]

[Booklist] ..> [Book]
[Booklist Browser] ..> [Booklist Editor]
[Booklist Browser] ..> [Booklist]
[Booklist Analyzer] ..> [Booklist Browser]
[Booklist Browser] ..> [Booklist Analyzer]


@enduml
