@startuml

component [Booklist] as Comp1
component [Book] as Comp2
component [Booklist Editor] as Comp3
component [Booklist Analyzer] as Comp4
component [Booklist Browser] as Comp5

[Comp1] ..> Comp2
[Comp3] ..> Comp4
[Comp3] ..> Comp1
[Comp5] ..> Comp3
[Comp5] ..> Comp4

@enduml
