@startuml
left to right direction
class Book {
  text
  name
  author
  isbn
  comment
  url
  authorurl
  referencelisturl
  referenceurl
  inLanguage
  category
  +method_tbd()
}

class Group {
  name
}

class Member {
  roles
}

User .. Member
Group .. Member
@enduml
